const people_data = [
    {'name': 'Abigail', 'birth_year': 1714, 'place_of_birth': 'New Haven, Connecticut, USA'},
    {'name': 'Agnes', 'birth_year': 1582, 'place_of_birth': 'Downton, Wiltshire, England, United Kingdom'},
    {'name': 'Alice', 'birth_year': 1465, 'place_of_birth': 'Wiltshire, England'},
    {'name': 'Alsea', 'birth_year': 1620, 'place_of_birth': 'Wethersfield, Hartford, Connecticut, USA'},
    {'name': 'Amy', 'birth_year': 1678, 'place_of_birth': 'Hartford, Hartford, Connecticut, USA'},
    {'name': 'Ann', 'birth_year': 1732, 'place_of_birth': 'Virginia, USA'},
    {'name': 'Anne', 'birth_year': 1724, 'place_of_birth': 'Watertown, Middlesex, Massachusetts, USA'},
    {'name': 'April', 'birth_year': 1560, 'place_of_birth': 'Broughton, Oxfordshire, England'},
    {'name': 'Ashley', 'birth_year': 1725, 'place_of_birth': 'Albemarle Parish, Surry, Virginia, USA'},
    {'name': 'Barbara', 'birth_year': 1775, 'place_of_birth': 'Of, Sheffield, Yorkshire, England'},
    {'name': 'Benjamin', 'birth_year': 1647, 'place_of_birth': 'New Haven, New Haven, Connecticut, USA'},
    {'name': 'Beriah', 'birth_year': 1658, 'place_of_birth': 'Middletown, Middlesex, Connecticut, USA'},
    {'name': 'Brenda Lee', 'birth_year': 1644, 'place_of_birth': 'Connecticut, USA'},
    {'name': 'Carla', 'birth_year': 1694, 'place_of_birth': 'Windsor, Hartford, Connecticut, USA'},
    {'name': 'Catherine', 'birth_year': 1752, 'place_of_birth': 'New Jersey, USA'},
    {'name': 'Charity', 'birth_year': 1727, 'place_of_birth': 'Surry, Virginia, USA'},
    {'name': 'Christopher', 'birth_year': 1574, 'place_of_birth': 'Biddenden, Kent, England, United Kingdom'},
    {'name': 'Daniel John', 'birth_year': 1739, 'place_of_birth': 'Tolland, Tolland, Connecticut, USA'},
    {'name': 'David', 'birth_year': 1694, 'place_of_birth': 'Barnstable, Barnstable, Massachusetts, USA'},
    {'name': 'Deborah', 'birth_year': 1729, 'place_of_birth': 'Tolland, Tolland, Connecticut, USA'},
    {'name': 'Dorothy', 'birth_year': 1655, 'place_of_birth': 'Connecticut, USA'},
    {'name': 'Ebenezer', 'birth_year': 1653, 'place_of_birth': 'Hartford, Hartford, Connecticut, USA'},
    {'name': 'Edla Brita', 'birth_year': 1714, 'place_of_birth': 'Middletown, Middlesex, Connecticut, USA'},
    {'name': 'Edward', 'birth_year': 1607, 'place_of_birth': 'Suffolk, England, United Kingdom'},
    {'name': 'Elden Ortel', 'birth_year': 1607, 'place_of_birth': 'Rhode Island, USA'},
    {'name': 'Elena', 'birth_year': 1684, 'place_of_birth': 'Hatfield, Hampshire, Massachusetts, USA'},
    {'name': 'Elisabeth', 'birth_year': 1630, 'place_of_birth': 'Boston, Suffolk, Massachusetts, USA'},
    {'name': 'Elisha', 'birth_year': 1610, 'place_of_birth': 'Fairfield, Fairfield, Connecticut, USA'},
    {'name': 'Eliza', 'birth_year': 1706, 'place_of_birth': 'Orleans, Barnstable, Massachusetts, USA'},
    {'name': 'Elizabeth', 'birth_year': 1591, 'place_of_birth': 'Heyford, Northamptonshire, England'},
    {'name': 'ElizAbeth', 'birth_year': 1611, 'place_of_birth': 'Lynn, Essex, Massachusetts, USA'},
    {'name': 'Elizabeth Eleanor', 'birth_year': 1591, 'place_of_birth': 'Roxbury, Suffolk, Massachusetts, USA'},
    {'name': 'Elizaveth', 'birth_year': 1627, 'place_of_birth': 'Hingham, Norfolkshire, England, United Kingdom'},
    {'name': 'Ellen', 'birth_year': 1612, 'place_of_birth': 'Northumberland, Virginia, USA'},
    {'name': 'Ellen wife of Digory Carwithen', 'birth_year': 1601, 'place_of_birth': 'Dorchester, Suffolk, Massachusetts, USA'},
    {'name': 'Ephraim', 'birth_year': 1686, 'place_of_birth': 'Glastonbury, Hartford, Connecticut, USA'},
    {'name': 'Esther', 'birth_year': 1567, 'place_of_birth': 'England, United Kingdom'},
    {'name': 'Eunice', 'birth_year': 1727, 'place_of_birth': 'Middleton, Essex, Massachusetts, USA'},
    {'name': 'Francis', 'birth_year': 1610, 'place_of_birth': 'England, United Kingdom'},
    {'name': 'Hanna', 'birth_year': 1627, 'place_of_birth': 'England, United Kingdom'},
    {'name': 'Hannah', 'birth_year': 1628, 'place_of_birth': 'Hingham, Norfolkshire, England, United Kingdom'},
    {'name': 'Hester', 'birth_year': 1616, 'place_of_birth': 'Wareham, Plymouth, Massachusetts, USA'},
    {'name': 'Howe', 'birth_year': 1639, 'place_of_birth': 'Hartford, Hartford, Connecticut, USA'},
    {'name': 'Huldah', 'birth_year': 1549, 'place_of_birth': 'London, London, England'},
    {'name': 'Isaac', 'birth_year': 1627, 'place_of_birth': 'Hatfield, Essex, England'},
    {'name': 'Isaaca Timothy Garner', 'birth_year': 1726, 'place_of_birth': 'Middletown, Middlesex, Connecticut, USA'},
    {'name': 'Isabell', 'birth_year': 1568, 'place_of_birth': 'Lincolnshire, England, United Kingdom'},
    {'name': 'Jacob', 'birth_year': 1618, 'place_of_birth': 'Plymouth, Plymouth, Massachusetts, USA'},
    {'name': 'Jane', 'birth_year': 1669, 'place_of_birth': 'Talbot, Maryland, USA'},
    {'name': 'Jenet', 'birth_year': 1720, 'place_of_birth': 'Tolland, Tolland, Connecticut, USA'},
    {'name': 'Jennifer', 'birth_year': 1621, 'place_of_birth': 'East Lothian, Scotland, United Kingdom'},
    {'name': 'Jessie', 'birth_year': 1614, 'place_of_birth': 'Hertfordshire, England, United Kingdom'},
    {'name': 'Jethro', 'birth_year': 1722, 'place_of_birth': 'Tolland, Tolland, Connecticut, USA'},
    {'name': 'Joanna', 'birth_year': 1652, 'place_of_birth': 'of, Linfield, Sussex, England'},
    {'name': 'Job Arnold', 'birth_year': 1731, 'place_of_birth': 'Tolland, Tolland, Connecticut, USA'},
    {'name': 'Jodie', 'birth_year': 1975, 'place_of_birth': 'Bountiful, Davis, Utah, USA'},
    {'name': 'John', 'birth_year': 1446, 'place_of_birth': 'Thorncombe, Devonshire, England, United Kingdom'},
    {'name': 'Jonathan', 'birth_year': 1674, 'place_of_birth': 'Middletown, Middlesex, Connecticut, USA'},
    {'name': 'Jordan', 'birth_year': 1701, 'place_of_birth': 'Barnstable, Barnstable, Massachusetts, USA'},
    {'name': 'Joseph', 'birth_year': 1601, 'place_of_birth': 'Plymouth, Plymouth, Massachusetts, USA'},
    {'name': 'Judith', 'birth_year': 1610, 'place_of_birth': 'Weymouth, Norfolk, Massachusetts, USA'},
    {'name': 'Juliana', 'birth_year': 1490, 'place_of_birth': 'Abergwili, Carmarthenshire, Wales, United Kingdom'},
    {'name': 'Katherine', 'birth_year': 1578, 'place_of_birth': 'Birstall, Yorkshire, England, United Kingdom'},
    {'name': 'Lydia', 'birth_year': 1763, 'place_of_birth': 'Kent Twp, Litchfield, Connecticut, USA'},
    {'name': 'Margaret', 'birth_year': 1600, 'place_of_birth': 'England, United Kingdom'},
    {'name': 'Margery', 'birth_year': 1615, 'place_of_birth': 'England, United Kingdom'},
    {'name': 'Margie', 'birth_year': 1590, 'place_of_birth': 'of, England'},
    {'name': 'Marian', 'birth_year': 1610, 'place_of_birth': 'Bedfordshire, England, United Kingdom'},
    {'name': 'Martha', 'birth_year': 1628, 'place_of_birth': 'Middlesex, England, United Kingdom'},
    {'name': 'Martha PECK', 'birth_year': 1904, 'place_of_birth': 'Avondale, Pueblo, Colorado, USA'},
    {'name': 'Mary', 'birth_year': 1640, 'place_of_birth': 'Connecticut, USA'},
    {'name': 'Melody Ann', 'birth_year': 1749, 'place_of_birth': 'Dutchess, New York, USA'},
    {'name': 'Miss', 'birth_year': 1610, 'place_of_birth': 'England, United Kingdom'},
    {'name': 'Nancy', 'birth_year': 1658, 'place_of_birth': 'Corner Hall, Hertfordshire, England, United Kingdom'},
    {'name': 'Naomi', 'birth_year': 1741, 'place_of_birth': 'of, Bunbury, Cheshire, England'},
    {'name': 'Nathaniel', 'birth_year': 1623, 'place_of_birth': 'Boston, Suffolk, Massachusetts, USA'},
    {'name': 'Nehemiah', 'birth_year': 1718, 'place_of_birth': 'Middleton, Essex, Massachusetts, USA'},
    {'name': 'Nelly', 'birth_year': 1721, 'place_of_birth': 'Middleton, Essex, Massachusetts, USA'},
    {'name': 'Norton of Kentshire', 'birth_year': 1735, 'place_of_birth': 'Middleton, Essex, Massachusetts, USA'},
    {'name': 'Ole', 'birth_year': 1725, 'place_of_birth': 'of, Doncaster, Yorkshire, England'},
    {'name': 'Phebe', 'birth_year': 1425, 'place_of_birth': 'Bristol, Avon, Gloucestershire, England'},
    {'name': 'Rachael', 'birth_year': 1724, 'place_of_birth': 'Tolland, Tolland, Connecticut, USA'},
    {'name': 'Rachell', 'birth_year': 1610, 'place_of_birth': 'Millbrook, Bedfordshire, England, United Kingdom'},
    {'name': 'Rhoda', 'birth_year': 1605, 'place_of_birth': 'Waltham Abbey, Essex, England, United Kingdom'},
    {'name': 'Rickey James', 'birth_year': 1616, 'place_of_birth': 'Plymouth, Plymouth, Massachusetts, USA'},
    {'name': 'Ruth', 'birth_year': 1622, 'place_of_birth': 'Hartford, Hartford, Connecticut, USA'},
    {'name': 'Samuel', 'birth_year': 1620, 'place_of_birth': 'Windsor, Hartford, Connecticut, USA'},
    {'name': 'Samuel David', 'birth_year': 1723, 'place_of_birth': 'Middletown, Middlesex, Connecticut, USA'},
    {'name': 'Sarah', 'birth_year': 1676, 'place_of_birth': 'Middletown, New Port, Rhode Island, USA'},
    {'name': 'Simon', 'birth_year': 1727, 'place_of_birth': 'Tolland, Tolland, Connecticut, USA'},
    {'name': 'Siri', 'birth_year': 1726, 'place_of_birth': 'Tolland, Tolland, Connecticut, USA'},
    {'name': 'Sophia', 'birth_year': 1801, 'place_of_birth': 'New Jersey, USA'},
]

export default people_data